language: none
services:
  - docker
install:
  - docker build -f tools/docker-amd64/Dockerfile . -t alvaroreig/pocket2kindle-amd64-debug
  - env >> .env-file-travis
script:
  # Checking that the docker image exist
  - docker images |grep pocket2kindle-amd64-debug
  # Executing the software and storing the output
  - docker run --rm --env-file=.env-file-travis alvaroreig/pocket2kindle-amd64-debug >> docker.output
  # Checking ebooks creation
  - cat docker.output | grep "creation=OK"
  # Checking that the email was sent
  - cat docker.output | grep "sent=OK"
