language: none
services:
  - docker
install:
  - docker build -f tools/docker-amd64/Dockerfile . -t alvaroreig/pocket2kindle-amd64-debug
script:
  - docker images |grep pocket2kindle-amd64-debug
  - docker run --rm alvaroreig/pocket2kindle-amd64-debug
